name: Java Program on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  run-java-program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and run Java program
        run: |
          chmod +x gradlew
          # Extract just the branch name from GITHUB_REF
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          
          # Print the extracted branch name (for verification)
          echo "Extracted branch name: $BRANCH_NAME"
          
          # Build and run Java program with the branch name
          ./gradlew -x test build
          java -jar build/libs/demo-0.0.1-SNAPSHOT.jar "$BRANCH_NAME"
#        run: |
#          chmod +x gradlew
#
#          ./gradlew -x test build  # Replace with your build command if using Gradle
#          java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
